import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Lang = "bn" | "en";
export type TextScale = "base" | "lg" | "xl";

type Dict = Record<string, { bn: string; en: string }>;

export const strings: Dict = {
  appName: { bn: "নিরাপদ ঢাকা", en: "Nirapod Dhaka" },
  tagline: {
    bn: "নাগরিকদের রিপোর্টে গড়া নিরাপত্তা মানচিত্র",
    en: "A public safety map built from citizen reports",
  },
  heroLead: {
    bn: "নিজের ভাষায় অপরাধ, দুর্ঘটনা ও রাস্তার সমস্যার কথা জানান। নিরাপদ ঢাকা আপনার রিপোর্ট বুঝে অগ্রাধিকার নির্ধারণ করে সঠিক কর্তৃপক্ষের কাছে দ্রুত পৌঁছে দেবে।",
    en: "Report crime, accidents and infrastructure hazards in your own words. Nirapod understands and prioritizes your reports for faster response.",
  },
  login: { bn: "লগ ইন", en: "Log in" },
  signup: { bn: "অ্যাকাউন্ট খুলুন", en: "Create account" },
  browseMap: { bn: "ম্যাপ দেখুন", en: "Browse the map" },
  logout: { bn: "লগ আউট", en: "Log out" },
  trustedBy: { bn: "তথ্য যায় যাদের কাছে", en: "Reports route to" },
  cityCorp: { bn: "সিটি কর্পোরেশন", en: "City Corporation" },
  dmb: { bn: "দুর্যোগ ব্যবস্থাপনা বোর্ড", en: "Disaster Management Board" },
  police: { bn: "পুলিশ", en: "Police" },
  loopView: { bn: "ঝুঁকি দেখুন", en: "View hazards" },
  loopViewSub: { bn: "আপনার এলাকার লাইভ ম্যাপ", en: "Live map of your area" },
  loopReport: { bn: "রিপোর্ট করুন", en: "Report one" },
  loopReportSub: { bn: "ছবি ও জিপিএস সহ", en: "With photo and GPS" },
  loopSos: { bn: "জরুরি এসওএস", en: "Emergency SOS" },
  loopSosSub: { bn: "নিকটতম থানায় খবর", en: "Alerts the nearest station" },
  findLostPhone: { bn: "হারানো ফোন খুঁজুন", en: "Find a lost phone" },
  noAccountNeeded: { bn: "লগ ইন ছাড়াই", en: "No login needed" },

  email: { bn: "ইমেইল", en: "Email" },
  password: { bn: "পাসওয়ার্ড", en: "Password" },
  fullName: { bn: "পূর্ণ নাম", en: "Full name" },
  phone: { bn: "মোবাইল নম্বর", en: "Mobile number" },
  emergencyContact: { bn: "জরুরি যোগাযোগ", en: "Emergency contact" },
  emergencyContactName: { bn: "জরুরি যোগাযোগের নাম", en: "Emergency contact name" },
  emergencyContactPhone: { bn: "জরুরি যোগাযোগের নম্বর", en: "Emergency contact number" },
  emergencyWhy: {
    bn: "এসওএস পাঠালে এই ব্যক্তিকে জানানো হবে।",
    en: "This person is alerted when you send an SOS.",
  },
  haveAccount: { bn: "অ্যাকাউন্ট আছে? লগ ইন করুন", en: "Already have an account? Log in" },
  needAccount: { bn: "নতুন? অ্যাকাউন্ট খুলুন", en: "New here? Create an account" },
  checkEmail: {
    bn: "ইমেইল দেখুন — নিশ্চিতকরণ লিঙ্ক পাঠানো হয়েছে।",
    en: "Check your email — we sent a confirmation link.",
  },

  all: { bn: "সব", en: "All" },
  crime: { bn: "অপরাধ", en: "Crime" },
  infrastructure: { bn: "অবকাঠামো", en: "Infrastructure" },
  accident: { bn: "দুর্ঘটনা", en: "Accident" },
  resolved: { bn: "সমাধান হয়েছে", en: "Resolved" },
  sent: { bn: "পাঠানো হয়েছে", en: "Sent" },
  received: { bn: "গৃহীত", en: "Received" },
  status: { bn: "অবস্থা", en: "Status" },
  confirm: { bn: "সত্য", en: "Confirm" },
  dispute: { bn: "ভুল", en: "Dispute" },
  reportHazard: { bn: "ঝুঁকি জানান", en: "Report a hazard" },
  newReport: { bn: "নতুন রিপোর্ট", en: "New report" },
  chooseType: { bn: "ধরন বাছুন", en: "Choose a type" },
  subtype: { bn: "কী ধরনের", en: "What kind" },
  description: { bn: "সংক্ষিপ্ত বিবরণ", en: "Short description" },
  addPhoto: { bn: "ছবি যোগ করুন", en: "Add a photo" },
  dragPin: { bn: "পিন সরিয়ে সঠিক জায়গা দিন", en: "Drag the pin to the exact spot" },
  submit: { bn: "পাঠান", en: "Send report" },
  sending: { bn: "পাঠানো হচ্ছে…", en: "Sending…" },
  reportSent: { bn: "রিপোর্ট পাঠানো হয়েছে", en: "Report sent" },
  cancel: { bn: "বাতিল", en: "Cancel" },
  loginToAct: { bn: "কাজ করতে লগ ইন করুন", en: "Log in to take action" },

  sos: { bn: "এসওএস", en: "SOS" },
  sosConfirmTitle: {
    bn: "লাইভ লোকেশনসহ এসওএস পাঠাবেন?",
    en: "Send SOS with your live location?",
  },
  sosConfirmBody: {
    bn: "নিকটতম থানা ও আপনার জরুরি যোগাযোগকে সঙ্গে সঙ্গে জানানো হবে।",
    en: "The nearest police station and your emergency contact will be alerted immediately.",
  },
  sendSos: { bn: "এসওএস পাঠান", en: "Send SOS" },
  sosLive: { bn: "এসওএস সক্রিয়", en: "SOS active" },
  sosNotified: {
    bn: "থানায় খবর দেওয়া হয়েছে · আপনার যোগাযোগকে জানানো হয়েছে",
    en: "Police station notified · your contact has been alerted",
  },
  nearestStation: { bn: "নিকটতম থানা", en: "Nearest police station" },
  liveLocation: { bn: "লাইভ অবস্থান", en: "Live location" },
  endSos: { bn: "এসওএস বন্ধ করুন", en: "End SOS" },

  callAmbulance: { bn: "নিকটতম অ্যাম্বুলেন্স ডাকুন", en: "Call nearest ambulance" },
  nearbyHospitals: { bn: "কাছের হাসপাতাল", en: "Nearby hospitals" },
  beds: { bn: "শয্যা", en: "Beds" },
  icu: { bn: "আইসিইউ", en: "ICU" },
  available: { bn: "খালি আছে", en: "Available" },
  full: { bn: "খালি নেই", en: "Full" },
  done: { bn: "ঠিক আছে", en: "Done" },

  lostPhoneTitle: { bn: "হারানো ফোন খুঁজুন", en: "Find a lost phone" },
  lostPhoneBody: {
    bn: "হারানো ফোনের নম্বর দিন। একটি লিঙ্ক তৈরি হবে — সেটি ফোনটির কাছে থাকা কাউকে পাঠান।",
    en: "Enter the number tied to the lost device. We generate a link you can share with whoever has the phone.",
  },
  phoneNumber: { bn: "ফোন নম্বর", en: "Phone number" },
  generateLink: { bn: "লিঙ্ক তৈরি করুন", en: "Generate link" },
  copyLink: { bn: "লিঙ্ক কপি করুন", en: "Copy link" },
  copied: { bn: "কপি হয়েছে", en: "Copied" },
  shareHint: {
    bn: "এসএমএস বা হোয়াটসঅ্যাপে পাঠান। লিঙ্ক খুললে ডিভাইসের সর্বশেষ অবস্থান দেখা যাবে।",
    en: "Send it over SMS or WhatsApp. Opening the link shows the device's last known location.",
  },
  locating: { bn: "অবস্থান নেওয়া হচ্ছে…", en: "Getting location…" },
  lastKnown: { bn: "সর্বশেষ জানা অবস্থান", en: "Last known location" },
  shareThisLocation: { bn: "এই অবস্থান শেয়ার করুন", en: "Share this location" },

  myReports: { bn: "আমার রিপোর্ট", en: "My reports" },
  profile: { bn: "প্রোফাইল", en: "Profile" },
  settings: { bn: "সেটিংস", en: "Settings" },
  save: { bn: "সংরক্ষণ", en: "Save" },
  saved: { bn: "সংরক্ষিত হয়েছে", en: "Saved" },
  noReports: { bn: "এখনও কোনো রিপোর্ট নেই", en: "No reports yet" },
  textSize: { bn: "লেখার আকার", en: "Text size" },
  highContrast: { bn: "উচ্চ কনট্রাস্ট", en: "High contrast" },
  normal: { bn: "স্বাভাবিক", en: "Normal" },
  large: { bn: "বড়", en: "Large" },
  xlarge: { bn: "অতি বড়", en: "Extra large" },
  language: { bn: "ভাষা", en: "Language" },

  dashboard: { bn: "ড্যাশবোর্ড", en: "Dashboard" },
  activeSos: { bn: "সক্রিয় এসওএস", en: "Active SOS alerts" },
  crimeFeed: { bn: "অপরাধ রিপোর্ট", en: "Crime reports" },
  hotspots: { bn: "চিহ্নিত হটস্পট", en: "Flagged hotspots" },
  markReceived: { bn: "গৃহীত চিহ্নিত করুন", en: "Mark received" },
  markResolved: { bn: "সমাধান হয়েছে", en: "Resolve" },
  viewOnMap: { bn: "ম্যাপে দেখুন", en: "View on map" },
  totalOpen: { bn: "মোট চলমান", en: "Total open" },
  resolvedThisMonth: { bn: "এ মাসে সমাধান", en: "Resolved this month" },
  overrideStatus: { bn: "অবস্থা পরিবর্তন", en: "Override status" },
  allStreams: { bn: "সব রিপোর্ট", en: "All streams" },
  infraOnly: { bn: "অবকাঠামো রিপোর্ট", en: "Infrastructure reports" },
  upvotes: { bn: "সমর্থন", en: "Confirmations" },
  noItems: { bn: "কিছু নেই", en: "Nothing here" },
  back: { bn: "ফিরে যান", en: "Back" },
  map: { bn: "ম্যাপ", en: "Map" },
  hotzone: { bn: "ঝুঁকিপূর্ণ এলাকা", en: "Hotzone" },

  /* ── Authority dashboard strings ── */
  dbSideLiveMap: { bn: "লাইভ ম্যাপ", en: "Live Map" },
  dbSideReports: { bn: "রিপোর্ট", en: "Reports" },
  dbSideTasks: { bn: "টাস্ক", en: "Tasks" },
  dbSideAnalytics: { bn: "বিশ্লেষণ", en: "Analytics" },
  dbSideNotifications: { bn: "বিজ্ঞপ্তি", en: "Notifications" },
  dbSideSettings: { bn: "সেটিংস", en: "Settings" },

  kpiOpenReports: { bn: "চলমান রিপোর্ট", en: "Open Reports" },
  kpiPending: { bn: "অপেক্ষমাণ", en: "Pending" },
  kpiResolvedToday: { bn: "আজ সমাধান", en: "Resolved Today" },
  kpiAvgResponse: { bn: "গড় প্রতিক্রিয়া", en: "Avg Response" },
  kpiNewToday: { bn: "আজ নতুন", en: "New Today" },
  kpiHighPriority: { bn: "উচ্চ অগ্রাধিকার", en: "High Priority" },
  kpiSosAlerts: { bn: "এসওএস সতর্কতা", en: "SOS Alerts" },
  kpiTotalReports: { bn: "মোট রিপোর্ট", en: "Total Reports" },

  actionReceive: { bn: "গ্রহণ করুন", en: "Receive" },
  actionAssign: { bn: "বরাদ্দ করুন", en: "Assign" },
  actionResolve: { bn: "সমাধান", en: "Resolve" },
  actionReject: { bn: "বাতিল", en: "Reject" },
  actionEscalate: { bn: "উচ্চতর পর্যায়ে পাঠান", en: "Escalate" },
  actionNavigate: { bn: "নেভিগেট", en: "Navigate" },
  actionContactReporter: { bn: "রিপোর্টারের সাথে যোগাযোগ", en: "Contact Reporter" },
  actionViewEvidence: { bn: "প্রমাণ দেখুন", en: "View Evidence" },
  actionAssignTeam: { bn: "দল বরাদ্দ", en: "Assign Team" },
  actionDeployResponse: { bn: "প্রতিক্রিয়া পাঠান", en: "Deploy Response" },
  actionRequestBackup: { bn: "ব্যাকআপ অনুরোধ", en: "Request Backup" },
  actionTransfer: { bn: "স্থানান্তর", en: "Transfer" },
  actionInProgress: { bn: "চলমান", en: "In Progress" },
  actionOpen: { bn: "খুলুন", en: "Open" },

  notifNewReport: { bn: "নতুন রিপোর্ট পাওয়া গেছে", en: "New report received" },
  notifSosActive: { bn: "এসওএস সক্রিয়", en: "SOS activated" },
  notifOfficerAssigned: { bn: "কর্মকর্তা বরাদ্দ হয়েছে", en: "Officer assigned" },
  notifReportVerified: { bn: "রিপোর্ট যাচাই হয়েছে", en: "Report verified" },
  notifHighPriority: { bn: "উচ্চ অগ্রাধিকার সতর্কতা", en: "High priority alert" },
  notifInfraEscalation: { bn: "অবকাঠামো উচ্চতর পর্যায়ে", en: "Infrastructure escalation" },
  notifToday: { bn: "আজ", en: "Today" },
  notifYesterday: { bn: "গতকাল", en: "Yesterday" },
  notifThisWeek: { bn: "এই সপ্তাহে", en: "This week" },

  chartWeeklyReports: { bn: "সাপ্তাহিক রিপোর্ট", en: "Weekly Reports" },
  chartMonthlyTrends: { bn: "মাসিক প্রবণতা", en: "Monthly Trends" },
  chartCategoryDist: { bn: "ক্যাটাগরি বিন্যাস", en: "Category Distribution" },
  chartResolutionRate: { bn: "সমাধানের হার", en: "Resolution Rate" },
  chartAvgResponseTime: { bn: "গড় প্রতিক্রিয়া সময়", en: "Avg Response Time" },
  chartDistrictPerf: { bn: "জেলা পারফরম্যান্স", en: "District Performance" },
  chartPeriod7d: { bn: "৭ দিন", en: "7 days" },
  chartPeriod30d: { bn: "৩০ দিন", en: "30 days" },
  chartPeriod90d: { bn: "৯০ দিন", en: "90 days" },

  searchGlobal: { bn: "রিপোর্ট, এলাকা, ক্যাটাগরি খুঁজুন…", en: "Search reports, areas, categories…" },
  searchNoResults: { bn: "কিছু পাওয়া যায়নি", en: "No results found" },

  rolePolice: { bn: "বাংলাদেশ পুলিশ", en: "Bangladesh Police" },
  roleDmb: { bn: "দুর্যোগ ব্যবস্থাপনা ব্যুরো", en: "Disaster Management Bureau" },
  roleCityCorp: { bn: "সিটি কর্পোরেশন", en: "City Corporation" },
  roleCitizen: { bn: "নাগরিক", en: "Citizen" },

  policeActiveSos: { bn: "সক্রিয় এসওএস", en: "Active SOS" },
  policeCrimeMap: { bn: "অপরাধ মানচিত্র", en: "Crime Map" },
  policeNearbyPatrols: { bn: "নিকটবর্তী টহল", en: "Nearby Patrols" },
  policeHighRisk: { bn: "উচ্চ ঝুঁকি হটস্পট", en: "High Risk Hotspots" },
  policeOfficerAssignment: { bn: "কর্মকর্তা বরাদ্দ", en: "Officer Assignments" },
  policeResponseTimeline: { bn: "প্রতিক্রিয়া টাইমলাইন", en: "Response Timeline" },

  dmbFloodReports: { bn: "বন্যা রিপোর্ট", en: "Flood Reports" },
  dmbFireReports: { bn: "অগ্নিকাণ্ড রিপোর্ট", en: "Fire Reports" },
  dmbCollapseReports: { bn: "ভবন ধস রিপোর্ট", en: "Collapse Reports" },
  dmbEmergencyReq: { bn: "জরুরি অনুরোধ", en: "Emergency Requests" },
  dmbHazardZones: { bn: "ঝুঁকিপূর্ণ এলাকা", en: "Hazard Zones" },
  dmbCoordination: { bn: "সমন্বয় কার্যক্রম", en: "Coordination Tasks" },

  ccExecOverview: { bn: "নির্বাহী সারসংক্ষেপ", en: "Executive Overview" },
  ccDeptPerformance: { bn: "বিভাগীয় পারফরম্যান্স", en: "Department Performance" },
  ccInfraIssues: { bn: "অবকাঠামো সমস্যা", en: "Infrastructure Issues" },
  ccRoadDamage: { bn: "রাস্তার ক্ষতি", en: "Road Damage" },
  ccDrainage: { bn: "ড্রেনেজ", en: "Drainage" },
  ccGarbage: { bn: "বর্জ্য", en: "Garbage" },
  ccStreetLights: { bn: "সড়কবাতি", en: "Street Lights" },
  ccPendingWorkOrders: { bn: "অপেক্ষমাণ কাজ", en: "Pending Work Orders" },
  ccMonthlyPerformance: { bn: "মাসিক পারফরম্যান্স", en: "Monthly Performance" },
  ccTopHotspots: { bn: "শীর্ষ হটস্পট", en: "Top Hotspots" },

  /* ── Redesigned Operations Dashboard Strings ── */
  aiPriorityQueue: { bn: "এআই অগ্রাধিকার কিউ", en: "AI Priority Queue" },
  aiPriorityDesc: { bn: "জরুরি মনোযোগ প্রয়োজন এমন রিপোর্ট", en: "Reports requiring immediate attention" },
  aiSafetyAssessmentTitle: { bn: "এআই সুরক্ষা অ্যাসেসমেন্ট", en: "AI Safety Assessment" },
  evidenceChecked: { bn: "প্রমাণ পরীক্ষিত", en: "Evidence checked" },
  visualEvidenceCheckComplete: { bn: "দৃশ্যমান প্রমাণ পরীক্ষা সম্পূর্ণ", en: "Visual evidence check complete" },
  liveSafetyMap: { bn: "লাইভ নিরাপত্তা মানচিত্র", en: "Live Safety Map" },
  liveSafetyMapSubtext: { bn: "ঢাকা শহরজুড়ে বর্তমান রিপোর্ট ও নিরাপত্তা পরিস্থিতি", en: "Current reports and safety conditions across Dhaka" },
  liveCrimeEmergencyMap: { bn: "লাইভ অপরাধ ও জরুরি মানচিত্র", en: "Live Crime & Emergency Map" },
  infraAccidentMap: { bn: "অবকাঠামো ও দুর্ঘটনা মানচিত্র", en: "Infrastructure & Accident Map" },
  crimeResponseQueue: { bn: "অপরাধ প্রতিক্রিয়া কিউ", en: "Crime Response Queue" },
  dmbResponseQueue: { bn: "ডিএমবি প্রতিক্রিয়া কিউ", en: "DMB Response Queue" },
  aiRiskPrototype: { bn: "এআই ঝুঁকি প্রোটোটাইপ", en: "AI Risk Prototype" },
  prototypeLabel: { bn: "প্রোটোটাইপ", en: "PROTOTYPE" },
  authorityWorkload: { bn: "কর্তৃপক্ষের কাজের চাপ", en: "Authority Workload" },
  activeReportsCount: { bn: "টি সক্রিয়", en: "active" },
  needsAttention: { bn: "মনোযোগ প্রয়োজন", en: "Needs attention" },
  immediateAttention: { bn: "অবিলম্বে মনোযোগ", en: "Immediate attention" },
  vsYesterday: { bn: "গতকাল থেকে", en: "vs yesterday" },
  clearStatusNotice: { bn: "বর্তমানে কোনো নতুন রিপোর্ট নেই। পরিস্থিতি স্বাভাবিক।", en: "Everything currently looks clear." },
  unableToLoadReports: { bn: "রিপোর্ট লোড করা যায়নি।", en: "Unable to load reports." },
  tryAgain: { bn: "আবার চেষ্টা করুন", en: "Try again" },
  policeOpsTitle: { bn: "পুলিশ জরুরি অপারেশন সেন্টার", en: "Police Emergency Operations Center" },
  dmbOpsTitle: { bn: "দুর্যোগ ও অবকাঠামো কার্যক্রম সেন্টার", en: "Disaster & Infrastructure Ops Center" },
  cityCorpOpsTitle: { bn: "ঢাকা সিটি কর্পোরেশন পাবলিক সেফটি সেন্টার", en: "Dhaka Safety Operations Center" },

  tlSubmitted: { bn: "রিপোর্ট জমা", en: "Report Submitted" },
  tlVerified: { bn: "সম্প্রদায় যাচাই", en: "Community Verified" },
  tlReceived: { bn: "কর্তৃপক্ষ গ্রহণ", en: "Authority Received" },
  tlAssigned: { bn: "কর্মকর্তা বরাদ্দ", en: "Officer Assigned" },
  tlInProgress: { bn: "কাজ চলছে", en: "Work In Progress" },
  tlResolved: { bn: "সমাধান হয়েছে", en: "Resolved" },
  tlClosed: { bn: "বন্ধ", en: "Closed" },

  verificationScore: { bn: "যাচাই স্কোর", en: "Verification Score" },
  internalNotes: { bn: "অভ্যন্তরীণ নোট", en: "Internal Notes" },
  addNote: { bn: "নোট যোগ করুন", en: "Add Note" },
  reportDetails: { bn: "রিপোর্টের বিবরণ", en: "Report Details" },
  evidence: { bn: "প্রমাণ", en: "Evidence" },
  nearbyReports: { bn: "নিকটবর্তী রিপোর্ট", en: "Nearby Reports" },
  assignedDepartment: { bn: "দায়িত্বপ্রাপ্ত বিভাগ", en: "Assigned Department" },
  bulkSelect: { bn: "একাধিক নির্বাচন", en: "Bulk Select" },
  filterBy: { bn: "ফিল্টার", en: "Filter by" },
  sortBy: { bn: "সাজান", en: "Sort by" },
  newest: { bn: "নতুন", en: "Newest" },
  oldest: { bn: "পুরাতন", en: "Oldest" },
  priority: { bn: "অগ্রাধিকার", en: "Priority" },
  minutes: { bn: "মিনিট", en: "min" },
  hours: { bn: "ঘণ্টা", en: "hrs" },

  searchPlaceholder: {
    bn: "বিপদ, রাস্তা, স্থান খুঁজুন...",
    en: "Search hazards, roads, places...",
  },
  dhaka: { bn: "ঢাকা", en: "Dhaka" },
  alerts: { bn: "অ্যালার্ট", en: "Alerts" },
  nearby: { bn: "আশপাশে", en: "Nearby" },
  reportCategories: { bn: "রিপোর্টের ক্যাটাগরি", en: "Report Categories" },
  mapLayers: { bn: "ম্যাপ লেয়ার", en: "Map Layers" },
  mapLabels: { bn: "ম্যাপ লেবেল", en: "Map Labels" },
  heatmap: { bn: "হিটম্যাপ", en: "Heatmap" },
  reportClusters: { bn: "রিপোর্ট ক্লাস্টার", en: "Report Clusters" },
  communityVerification: { bn: "কমিউনিটি যাচাইকরণ", en: "Community Verification" },
  verifiedByPrefix: { bn: "যাচাই করেছেন", en: "Verified by" },
  verifiedBySuffix: { bn: "জন", en: "people" },
  assignedTo: { bn: "দায়িত্বপ্রাপ্ত", en: "Assigned To" },
  cityCorpName: { bn: "সিটি কর্পোরেশন, ঢাকা", en: "City Corporation, Dhaka" },
  workInProgress: { bn: "কাজ চলছে", en: "Work in progress" },
  actions: { bn: "পদক্ষেপ", en: "Actions" },
  share: { bn: "শেয়ার", en: "Share" },
  navigateAction: { bn: "নেভিগেট", en: "Navigate" },
  activityTimeline: { bn: "কাজের টাইমলাইন", en: "Activity Timeline" },
  reportSubmitted: { bn: "রিপোর্ট জমা দেওয়া হয়েছে", en: "Report submitted" },
  verifiedByCommunity: { bn: "কমিউনিটি দ্বারা যাচাইকৃত", en: "Verified by community" },
  justNow: { bn: "এইমাত্র", en: "Just now" },
  assignedToAuthority: { bn: "কর্তৃপক্ষের কাছে হস্তান্তরিত", en: "Assigned to authority" },
  whatToReport: { bn: "আপনি কী রিপোর্ট করতে চান?", en: "What do you want to report?" },
  selectCategory: {
    bn: "সমস্যার সাথে সবচেয়ে ভালো মেলে এমন ক্যাটাগরি বেছে নিন",
    en: "Select the category that best matches the issue",
  },
  takeClearPhoto: { bn: "একটি পরিষ্কার ছবি তুলুন", en: "Take a clear photo" },
  makeSureVisible: {
    bn: "নিশ্চিত করুন সমস্যাটি স্পষ্টভাবে দেখা যাচ্ছে",
    en: "Make sure the issue is clearly visible",
  },
  addDetails: { bn: "বিস্তারিত যোগ করুন", en: "Add details" },
  whereIsHappening: { bn: "কোথায় এবং কী ঘটছে?", en: "Where and what is happening?" },
  skipStep: { bn: "এই ধাপ এড়িয়ে যান", en: "Skip this step" },
  next: { bn: "পরবর্তী", en: "Next" },
  inProgress: { bn: "চলমান", en: "In Progress" },
  rejected: { bn: "বাতিল", en: "Rejected" },
  verified: { bn: "যাচাইকৃত", en: "verified" },
  descriptionRequired: { bn: "সংক্ষিপ্ত বিবরণ লিখুন", en: "Add a short description" },
  locationUpdating: { bn: "অবস্থান হালনাগাদ হচ্ছে", en: "Location still updating" },

  howItWorks: { bn: "কিভাবে কাজ করে", en: "How it works" },
  features: { bn: "সুবিধাসমূহ", en: "Features" },
  stats: { bn: "পরিসংখ্যান", en: "Statistics" },
  helpCenter: { bn: "সাহায্য কেন্দ্র", en: "Help Center" },
  heroTitle1: { bn: "প্রতিটি রিপোর্ট", en: "Every report" },
  heroTitle2: { bn: "কারও না কারও", en: "saves" },
  heroTitle3: { bn: "জীবন রক্ষা করে", en: "someone's life" },
  heroDesc: {
    bn: "স্বাভাবিক ভাষায় রিপোর্ট করুন, নিরাপদ ঢাকা বুঝতে পারে।\nআপনার রিপোর্ট বিশ্লেষণ করে কর্তৃপক্ষকে দ্রুত ব্যবস্থা নিতে সাহায্য করে।",
    en: "Report in your own words. Nirapod understands.\nWe structure and prioritize your reports for rapid authority action.",
  },
  reportNow: { bn: "রিপোর্ট করুন", en: "Report Now" },
  viewLiveMap: { bn: "লাইভ ম্যাপ দেখুন", en: "View Live Map" },
  emergencySos: { bn: "জরুরি SOS", en: "Emergency SOS" },
  safe: { bn: "নিরাপদ", en: "Safe" },
  reliable: { bn: "নির্ভরযোগ্য", en: "Reliable" },
  forEveryone: { bn: "সবার জন্য", en: "For Everyone" },
  workingTogether: { bn: "একসাথে কাজ করছে", en: "Working Together" },
  bdPolice: { bn: "বাংলাদেশ পুলিশ", en: "Bangladesh Police" },
  healthEmergency: { bn: "স্বাস্থ্য ও জরুরি সেবা", en: "Health & Emergency Services" },
  totalReports: { bn: "মোট রিপোর্ট", en: "Total Reports" },
  resolvedCount: { bn: "সমাধান হয়েছে", en: "Resolved" },
  communityConfirmation: { bn: "সম্প্রদায়ের নিশ্চিতকরণ", en: "Community Confirmations" },
  activeCitizens: { bn: "সক্রিয় নাগরিক", en: "Active Citizens" },
  step1Title: { bn: "স্মার্ট রিপোর্টিং", en: "Smart Reporting" },
  step1Desc: { bn: "বাংলা, বাংলিশ বা ইংরেজিতে ঘটনাটি লিখে জানান। নিরাপদ ঢাকা স্বয়ংক্রিয়ভাবে আপনার রিপোর্টের ধরন ও জরুরি অবস্থা বুঝে নেবে।", en: "Describe what happened in Bangla, Banglish or English. Nirapod structures your report and identifies its urgency." },
  step2Title: { bn: "ভয়েস বা টেক্সট", en: "Text or Voice" },
  step2Desc: {
    bn: "লিখে বা স্বাভাবিক কথায় রিপোর্ট করুন। পাঠানোর আগে আপনি নিজেই যাচাই করে নিতে পারবেন।",
    en: "Report naturally by typing or speaking. Your voice is transcribed and analyzed before you review the result.",
  },
  step3Title: { bn: "প্রমাণসহ রিপোর্ট", en: "Report with Evidence" },
  step3Desc: {
    bn: "ছবি যুক্ত করুন। সিস্টেম আপনার বর্ণনার সাথে ছবির মিল বিশ্লেষণ করে রিপোর্টের সত্যতা যাচাই করতে সাহায্য করবে।",
    en: "Attach a photo and Nirapod can analyze visual evidence alongside your text description.",
  },
  step4Title: { bn: "স্মার্ট পদক্ষেপ", en: "Smarter Response" },
  step4Desc: {
    bn: "রিপোর্টের ঝুঁকি ও অগ্রাধিকার হিসেব করে সঠিক কর্তৃপক্ষের ড্যাশবোর্ডে পাঠানো হয়, যাতে দ্রুত কাজ হয়।",
    en: "Reports are structured and prioritized so authorities can focus on higher-risk incidents first.",
  },
  recentActivity: { bn: "সাম্প্রতিক কার্যক্রম", en: "Recent Activity" },
  seeAll: { bn: "সব দেখুন", en: "See All" },
  openManhole: { bn: "খোলা ম্যানহোল", en: "Open Manhole" },
  dhanmondiDhaka: { bn: "ধানমন্ডি, ঢাকা", en: "Dhanmondi, Dhaka" },
  twoMinsAgo: { bn: "২ মিনিট আগে", en: "2 mins ago" },
  statusConfirmed: { bn: "নিশ্চিত হয়েছে", en: "Confirmed" },
  eighteenConfirmed: { bn: "১৮ জন নিশ্চিত করেছেন", en: "18 people confirmed" },
  roadAccidentLabel: { bn: "সড়ক দুর্ঘটনা", en: "Road Accident" },
  farmgateDhaka: { bn: "ফার্মগেট, ঢাকা", en: "Farmgate, Dhaka" },
  sixMinsAgo: { bn: "৬ মিনিট আগে", en: "6 mins ago" },
  policeNotified: { bn: "পুলিশকে জানানো হয়েছে", en: "Police Notified" },
  policeActionTaken: { bn: "পুলিশ ব্যবস্থা নিয়েছে", en: "Police took action" },
  brokenDrain: { bn: "ড্রেন ভাঙা", en: "Broken Drain" },
  mirpur10Dhaka: { bn: "মিরপুর ১০, ঢাকা", en: "Mirpur 10, Dhaka" },
  twentyMinsAgo: { bn: "২০ মিনিট আগে", en: "20 mins ago" },
  underAuthorityReview: { bn: "কর্তৃপক্ষের রিভিউতে", en: "Under Authority Review" },
  cityCorpLooking: { bn: "সিটি কর্পোরেশন দেখছে", en: "City Corporation is looking" },
  snatchingAttempt: { bn: "ছিনতাইয়ের চেষ্টা", en: "Snatching Attempt" },
  gulshan1Dhaka: { bn: "গুলশান ১, ঢাকা", en: "Gulshan 1, Dhaka" },
  thirtyFiveMinsAgo: { bn: "৩৫ মিনিট আগে", en: "35 mins ago" },
  thirtyTwoConfirmed: { bn: "৩২ জন নিশ্চিত করেছেন", en: "32 people confirmed" },
  easyFastForAll: { bn: "সহজ, দ্রুত, সবার জন্য", en: "Easy, Fast, For Everyone" },
  reportInFewSteps: { bn: "মাত্র কয়েকটি ধাপে রিপোর্ট করুন", en: "Report in just a few steps" },
  liveMapLabel: { bn: "লাইভ ম্যাপ", en: "Live Map" },
  createReportLabel: { bn: "রিপোর্ট তৈরি করুন", en: "Create Report" },
  locationDhanmondi: { bn: "স্থান: ধানমন্ডি, ঢাকা", en: "Location: Dhanmondi, Dhaka" },
  addPhotoLabel: { bn: "ছবি যোগ করুন", en: "Add a Photo" },
  sendReportLabel: { bn: "রিপোর্ট পাঠান", en: "Send Report" },
  reportSentTitle: { bn: "রিপোর্ট পাঠানো হয়েছে", en: "Report Sent" },
  reportSentDesc: {
    bn: "আপনার রিপোর্ট কর্তৃপক্ষের কাছে পাঠানো হয়েছে। ধন্যবাদ!",
    en: "Your report has been sent to the authorities. Thank you!",
  },
  okButton: { bn: "ঠিক আছে", en: "Okay" },
  alertPoliceOneTap: { bn: "এক চাপে পুলিশকে জানান", en: "Alert police with one tap" },
  shareRealTimeLocation: { bn: "বাস্তব সময়ে অবস্থান শেয়ার", en: "Share location in real-time" },
  findByPhoneNumber: { bn: "ফোন নম্বর দিয়ে খুঁজে পান", en: "Find using phone number" },
  safePrivate: { bn: "নিরাপদ ও গোপনীয়", en: "Safe & Private" },
  yourDataSecure: { bn: "আপনার তথ্য সুরক্ষিত", en: "Your data is secure" },
  citizensVoice: { bn: "নাগরিকদের কথা", en: "Citizens' Voice" },
  citizensVoiceDesc: {
    bn: "যারা প্রতিদিন এই প্ল্যাটফর্ম ব্যবহার করে শহরকে নিরাপদ করছেন তাদের অভিজ্ঞতা শুনুন।",
    en: "Hear from those who make the city safer every day using this platform.",
  },
  testimonial1: {
    bn: "আমাদের স্কুলের সামনে খোলা ম্যানহোলটি দুইদিনের মধ্যে সমাধান করা হয়েছে। প্ল্যাটফর্মটি সত্যিই কাজ করে।",
    en: "The open manhole in front of our school was fixed in two days. This platform really works.",
  },
  name1: { bn: "রাফিয়া তাসনিম", en: "Rafia Tasnim" },
  role1: { bn: "বাসিন্দা, ধানমন্ডি", en: "Resident, Dhanmondi" },
  testimonial2: {
    bn: "আমরা লোকেশন পাওয়ার সাথে সাথেই ঘটনাস্থলে পৌঁছে যেতে পারি। এই প্ল্যাটফর্মটি আমাদের কাজকে দ্রুততর করেছে।",
    en: "We can reach the spot immediately upon receiving the location. This platform has sped up our work.",
  },
  name2: { bn: "ইন্সপেক্টর মাহমুদ হাসান", en: "Inspector Mahmud Hasan" },
  testimonial3: {
    bn: "নাগরিকদের রিপোর্ট আমাদের কাজ অনেক সহজ করে দেয়। আমরা এখন সঠিক জায়গায় ফোকাস করতে পারি।",
    en: "Citizen reports make our job much easier. We can now focus on the right places.",
  },
  name3: { bn: "মেহেদী হাসান", en: "Mehedi Hasan" },
  footerDesc: {
    bn: "একসাথে গড়ি নিরাপদ বাংলাদেশ। অপরাধ, দুর্ঘটনা ও অবকাঠামোগত সমস্যা রিপোর্ট করুন। আপনার একটি সতর্কবার্তা বাঁচাতে পারে একটি প্রাণ।",
    en: "Let's build a safer Bangladesh together. Report crimes, accidents and infrastructure issues. Your one alert can save a life.",
  },
  platform: { bn: "প্ল্যাটফর্ম", en: "Platform" },
  authoritiesTitle: { bn: "কর্তৃপক্ষ", en: "Authorities" },
  helpAndInfo: { bn: "সাহায্য ও তথ্য", en: "Help & Info" },
  legal: { bn: "আইনি", en: "Legal" },
  emergencyNumbers: { bn: "জরুরি নাম্বারসমূহ", en: "Emergency Numbers" },
  contact: { bn: "যোগাযোগ", en: "Contact" },
  accessibility: { bn: "অ্যাক্সেসিবিলিটি", en: "Accessibility" },
  termsOfUse: { bn: "ব্যবহারের শর্তাবলী", en: "Terms of Use" },
  privacyPolicy: { bn: "গোপনীয়তা নীতি", en: "Privacy Policy" },
  cookiePolicy: { bn: "কুকি নীতি", en: "Cookie Policy" },
  copyright: {
    bn: "© ২০২৬ নিরাপদ শহর. সর্বস্বত্ব সংরক্ষিত।",
    en: "© 2026 Nirapod Dhaka. All rights reserved.",
  },
  aboutUs: { bn: "আমাদের সম্পর্কে", en: "About Us" },
  terms: { bn: "শর্তাবলী", en: "Terms" },
  verifyPhotoTitle: { bn: "ছবি দিয়ে যাচাই করুন", en: "Verify with Photo Evidence" },
  verifyPhotoDesc: { bn: "আমাদের এআই আপনার রিপোর্ট বিশ্লেষণ করেছে। এখন যাচাই করার জন্য অনুগ্রহ করে সমস্যার একটি ছবি যুক্ত করুন।", en: "Our AI has analyzed your report. Now, please attach an image of the hazard to verify it." },
  photoAttached: { bn: "ছবি যুক্ত করা হয়েছে", en: "Photo Attached" },
  removePhoto: { bn: "ছবি মুছুন", en: "Remove Photo" },
  photoEvidenceAttached: { bn: "ছবির প্রমাণ যুক্ত করা হয়েছে", en: "Photo Evidence Attached" },
  aiAssessmentTitle: { bn: "অপারেশনাল সেফটি অ্যাসেসমেন্ট", en: "Operational Safety Assessment" },
  aiAssessmentDesc: { bn: "নিরাপদ এআই এর কাঠামোগত সুপারিশ — নিশ্চিত করার আগে রিভিউ করুন।", en: "Nirapod AI structured recommendation — review before confirming." },
  editableTranscript: { bn: "সম্পাদনাযোগ্য বর্ণনা", en: "Editable Description Transcript" },
  analyzeBtn: { bn: "নিরাপদ এআই দিয়ে বিশ্লেষণ করুন", en: "Analyze with Nirapod AI" },
  analyzing: { bn: "বিশ্লেষণ চলছে…", en: "Analyzing…" },
  skipAiBtn: { bn: "এআই বাদ দিয়ে ম্যানুয়ালি রিপোর্ট করুন", en: "Skip AI & Report Manually" },
  reviewRecommend: { bn: "অনুগ্রহ করে উপরের সুপারিশটি রিভিউ করুন বা পরিবর্তন করতে এডিট বাটনে ক্লিক করুন।", en: "Please review recommendation above or click Edit to override." },
  verifyImageBtn: { bn: "ছবি যাচাই করুন", en: "Verify Image" },
  verifyingBtn: { bn: "যাচাই করা হচ্ছে...", en: "Verifying..." },
  reportIssueTitle: { bn: "নিরাপত্তা সমস্যা রিপোর্ট করুন", en: "Report a Safety Issue" },
  reportIssueDesc: { bn: "বাংলা, বাংলিশ বা ইংরেজিতে বর্ণনা করুন অথবা ভয়েস রেকর্ড করুন।", en: "Describe in Bangla, Banglish, English, or record voice." },
  recordVoiceBtn: { bn: "ভয়েস রেকর্ড করুন", en: "Record Voice" },
  stopRecordingBtn: { bn: "রেকর্ডিং বন্ধ করুন", en: "Stop Recording" },
  confirmLocationTitle: { bn: "লোকেশন নিশ্চিত করুন", en: "Confirm Location" },
  confirmLocationDesc: { bn: "ম্যাপে পিন টেনে সঠিক লোকেশন নির্ধারণ করুন।", en: "Drag pin to set exact hazard location on map." },
  aiIntelligence: { bn: "এআই সেফটি ইন্টেলিজেন্স", en: "AI Safety Intelligence" },
  recommendation: { bn: "সুপারিশ", en: "Recommendation" },
  aiPriority: { bn: "এআই অগ্রাধিকার", en: "AI Priority" },
  categoryLabel: { bn: "ক্যাটাগরি", en: "Category" },
  severityLabel: { bn: "তীব্রতা", en: "Severity" },
  urgencyLabel: { bn: "জরুরী", en: "Urgency" },
  recAuthority: { bn: "প্রস্তাবিত কর্তৃপক্ষ", en: "Rec. Authority" },
  modelConfidence: { bn: "মডেল কনফিডেন্স", en: "Model Confidence" },
  modelEstimationDesc: { bn: "সিমেন্টিক প্যাটার্ন ম্যাচিংয়ের উপর ভিত্তি করে মডেল এস্টিমেশন স্কোর (শতভাগ নির্ভুলতার গ্যারান্টি নেই)।", en: "Model estimation score based on semantic pattern matching (not a correctness guarantee)." },
  visualEvidenceAnalysis: { bn: "ভিজ্যুয়াল প্রমান বিশ্লেষণ", en: "Visual Evidence Analysis" },
  photoEvidenceFallback: { bn: "ছবির প্রমাণ যুক্ত করা হয়েছে।", en: "Photo evidence attached." },
  visualDiscrepancyNotice: { bn: "ভিজ্যুয়াল অমিল সতর্কতা:", en: "Visual Discrepancy Notice:" },
  photoEvidenceFallbackDesc: { bn: "ছবির প্রমাণের সাথে রিপোর্ট করা ক্যাটাগরি পুরোপুরি নাও মিলতে পারে। আপনি চূড়ান্ত সিদ্ধান্ত নিতে পারেন।", en: "Photo evidence may not fully match the reported category. You remain the final decision-maker." },
  safetyAssessmentSummary: { bn: "নিরাপত্তা মূল্যায়নের সারসংক্ষেপ:", en: "Safety Assessment Summary:" },
  aiRecommendNotice: { bn: "শুধুমাত্র এআই সুপারিশ — নিশ্চিত করার আগে সমস্ত বিস্তারিত রিভিউ করুন।", en: "AI recommendation only — please review all details before confirming." },
  editDetailsBtn: { bn: "বিস্তারিত এডিট করুন", en: "Edit Details" },
  confirmLocationBtn: { bn: "নিশ্চিত করুন এবং লোকেশন নির্বাচন করুন", en: "Confirm & Select Location" },

  // ── New citizen report flow ────────────────────────────────────────────────
  step1Report: { bn: "রিপোর্ট", en: "Report" },
  step2Photo: { bn: "ছবি", en: "Photo" },
  step3Verify: { bn: "যাচাই", en: "Verify" },
  step4Submit: { bn: "জমা দিন", en: "Submit" },
  incidentDetailsTitle: { bn: "ঘটনার বিবরণ", en: "Incident details" },
  incidentDetailsDesc: {
    bn: "ঘটনাটি কী ও কোথায় হচ্ছে সংক্ষেপে লিখুন। বাংলা, বাংলিশ বা ইংরেজি — যেকোনো ভাষায় লিখতে পারেন।",
    en: "Briefly describe what is happening and where. Bangla, Banglish or English — write in whichever is fastest.",
  },
  describePlaceholder: {
    bn: "কী হচ্ছে তা লিখুন…\nযেমন: ei rastay ekta open manhole ase, rate dekha jay na",
    en: "Describe what is happening…\nExample: ei rastay ekta open manhole ase, rate dekha jay na",
  },
  incidentCategoryLabel: { bn: "ঘটনার ধরন", en: "Incident category" },
  locationLabel: { bn: "লোকেশন", en: "Location" },
  tapToAdjust: { bn: "ম্যাপে ট্যাপ করে সরান", en: "Tap map to adjust pin" },
  voiceInputOptional: { bn: "ভয়েস ইনপুট (ঐচ্ছিক)", en: "Voice input (optional)" },
  charsCounter: { bn: "{n}/১০০০ অক্ষর", en: "{n}/1000 characters" },
  descriptionTooShort: { bn: "অনুগ্রহ করে অন্তত কিছু বিবরণ লিখুন।", en: "Please provide at least a short description." },
  aiWillInferCategory: {
    bn: "ক্যাটেগরি ও অগ্রাধিকার আমাদের AI নিজেই নির্ধারণ করবে।",
    en: "Our AI will infer the category, severity and priority automatically.",
  },
  continueToPhoto: { bn: "ছবিতে যান", en: "Continue to Photo" },

  photoStepTitle: { bn: "ভিজ্যুয়াল প্রমাণ", en: "Visual evidence" },
  photoRequiredBadge: { bn: "ছবি আবশ্যক", en: "Photo required" },
  photoHelpText: {
    bn: "ঘটনাস্থল বা হ্যাজার্ডের একটি পরিষ্কার ছবি আপলোড করুন।",
    en: "Upload a clear photo of the reported incident or hazard location.",
  },
  choosePhoto: { bn: "ছবি বাছুন", en: "Choose Photo" },
  replacePhoto: { bn: "ছবি পরিবর্তন করুন", en: "Replace Photo" },
  dragOrDrop: { bn: "অথবা এখানে ছবি টেনে আনুন", en: "or drag and drop an image here" },
  photoQualityOk: { bn: "ছবি গ্রহণযোগ্য", en: "Photo quality OK" },
  photoFileSize: { bn: "{kb} কেবি", en: "{kb} KB" },
  backToReport: { bn: "বিবরণে ফিরুন", en: "Back to Report" },

  // Visual verification card
  visualVerification: { bn: "ভিজ্যুয়াল যাচাইকরণ", en: "Visual verification" },
  visualVerificationComplete: {
    bn: "ভিজ্যুয়াল যাচাই সম্পন্ন",
    en: "Visual verification complete",
  },
  visualVerificationInProgress: {
    bn: "ভিজ্যুয়াল প্রমাণ বিশ্লেষণ হচ্ছে…",
    en: "Analyzing visual evidence…",
  },
  visualVerificationProgressDesc: {
    bn: "আপনার ছবি ও রিপোর্টের সাথে মিলিয়ে দেখা হচ্ছে",
    en: "Comparing your photo with your report",
  },
  visualVerificationHelp: {
    bn: "সাধারণত কয়েক সেকেন্ড সময় লাগে।",
    en: "This usually takes a few seconds.",
  },
  statusAcceptable: { bn: "গ্রহণযোগ্য", en: "Acceptable" },
  statusMismatch: { bn: "অমিল", en: "Mismatch" },
  statusUncertain: { bn: "অনিশ্চিত", en: "Uncertain" },
  statusNotRelevant: { bn: "প্রাসঙ্গিক নয়", en: "Not relevant" },
  statusQualityLow: { bn: "ছবির মান যথেষ্ট নয়", en: "Image quality low" },
  statusFailed: { bn: "বিশ্লেষণ ব্যর্থ", en: "Analysis failed" },
  aiDetected: { bn: "এআই শনাক্ত করেছে", en: "AI detected" },
  yourReport: { bn: "আপনার রিপোর্ট", en: "Your report" },
  consistencyCheck: { bn: "ছবি রিপোর্টের সাথে সামঞ্জস্যপূর্ণ মনে হচ্ছে", en: "Image appears consistent with your report" },
  categoryLooksRelevant: { bn: "ক্যাটাগরি প্রাসঙ্গিক মনে হচ্ছে", en: "Category appears relevant" },
  confidenceLabel: { bn: "কনফিডেন্স", en: "Confidence" },
  aiSummary: { bn: "এআই সারসংক্ষেপ", en: "AI summary" },
  continueToReview: { bn: "রিভিউতে যান", en: "Continue to Review" },

  mismatchTitle: { bn: "ছবি রিপোর্টের সাথে সামঞ্জস্যপূর্ণ মনে হচ্ছে না", en: "Image does not appear consistent with this report" },
  mismatchExplanation: {
    bn: "আপলোড করা ছবিতে রিপোর্টে বর্ণিত ঘটনার চিহ্ন পাওয়া যায়নি।",
    en: "The uploaded image does not appear to show the incident described in your report.",
  },
  aiDetectedInImage: { bn: "ছবিতে শনাক্ত হয়েছে", en: "AI detected in image" },
  yourReportDescribes: { bn: "আপনার রিপোর্টে আছে", en: "Your report describes" },
  uploadDifferentPhoto: { bn: "অন্য ছবি আপলোড করুন", en: "Upload Different Photo" },

  uncertainTitle: { bn: "ছবি যাচাই করা যাচ্ছে না", en: "Unable to verify this image" },
  uncertainExplanation: {
    bn: "ছবিটি যথেষ্ট পরিষ্কার নয় বলে রিপোর্টের সাথে মিলিয়ে দেখা সম্ভব হচ্ছে না।",
    en: "The image is too unclear to determine whether it matches the reported incident.",
  },
  uploadClearerPhoto: { bn: "আরও পরিষ্কার ছবি আপলোড করুন", en: "Upload Clearer Photo" },

  qualityLowTitle: { bn: "ছবির মান যাচাইয়ের জন্য যথেষ্ট নয়", en: "Photo quality is too low for verification" },
  qualityLowExplanation: {
    bn: "ছবি অনেক অন্ধকার / ঝাপসা / ছোট অথবা প্রাসঙ্গিক কন্টেন্ট নেই।",
    en: "The photo is too dark, blurry, small, or does not contain recognisable content.",
  },

  apiFailedTitle: { bn: "ভিজ্যুয়াল যাচাইকরণ সাময়িকভাবে বন্ধ আছে", en: "Visual verification is temporarily unavailable" },
  apiFailedExplanation: {
    bn: "এখন রিপোর্ট জমা দেওয়া যাবে না — ছবি যাচাই বাধ্যতামূলক।",
    en: "The report cannot proceed because visual verification is mandatory.",
  },
  tryAgain: { bn: "আবার চেষ্টা করুন", en: "Try Again" },

  // Demo evidence check flow
  evidenceCheckTitle: { bn: "দৃশ্যমান প্রমাণ যাচাই", en: "Visual Evidence Check" },
  evidenceCheckSubtitle: { bn: "আপনার রিপোর্টের সাথে ঘটনার সামঞ্জস্য মিলিয়ে দেখা হচ্ছে…", en: "Checking the submitted photo against your report…" },
  evidenceCheckComplete: { bn: "প্রমাণ যাচাই সম্পন্ন", en: "Visual Evidence Check Complete" },
  evidenceCheckMismatchTitle: { bn: "প্রমাণ সামঞ্জস্যুতা মিলেনি", en: "Evidence does not appear consistent" },
  evidenceCheckMismatchDesc: { bn: "আপলোড করা হত্যের সাথে রিপোর্টে বর্ণিত প্রমাণীয় মিল নেই।", en: "The uploaded photo does not appear to be relevant to the incident in your report." },
  evidenceCheckUncertainTitle: { bn: "প্রমাণ নির্ণয় করা যাচ্ছে না", en: "Unable to verify the evidence" },
  evidenceCheckUncertainDesc: { bn: "আরও পরিষ্কার বা স্পষ্ট ছবি আপলোড করুন।", en: "Please upload a clearer or more directly relevant photo." },
  reportedIncident: { bn: "রিপোর্ট করা ঘটনা", en: "Reported incident" },
  evidenceStatus: { bn: "প্রমাণের অবস্থা", en: "Evidence status" },
  evidenceDoesNotMatch: { bn: "মিল খুজে পাওয়া যায়নি", en: "Does not appear to match" },
  evidenceConsistent: { bn: "প্রমাণ রিপোর্টের সাথে সামঞ্জস্যপূর্ণ", en: "Evidence appears consistent with your report" },
  photoSubmitted: { bn: "ছবি প্রেরণ করা হয়েছে", en: "Photo submitted" },
  evidenceConsistency: { bn: "প্রমাণের সামঞ্জস্যতা", en: "Evidence consistency" },
  consistencyHigh: { bn: "উচ্চ", en: "High" },
  aiUnderstoodTitle: { bn: "এআই আপনার রিপোর্ট বুঝেছে", en: "AI understood your report" },
  evidenceCheckHint: { bn: "এই উত্তোল দিয়ে আপনার হত্যের সাথে মিলানো যাচাই করা হচ্ছে।", en: "The evidence is being checked against the incident identified from your report." },
  humanReviewRequired: { bn: "মানব পর্যালোচনা প্রয়োজন।", en: "Human review required." },
  scanStep_report: { bn: "রিপোর্ট বোঝা হয়েছে", en: "Report understood" },
  scanStep_incident: { bn: "ঘটনা চিহ্নিত হয়েছে", en: "Incident identified" },
  scanStep_evidence: { bn: "প্রমাণ যাচাই সম্পন্ন", en: "Evidence checked" },

  // Demo AI route (BN/EN)
  demoAiBadge: { bn: "প্রোটোটাইপ", en: "PROTOTYPE" },
  demoAiTitle: { bn: "এআই ডেমো মোড", en: "AI Demo Mode" },
  demoAiSubtitle: { bn: "মল্টভাষীয় ন্যারো এবং প্রোটোটাইপ সামর্থ্য। প্রমাণ এআই নির্মাণের কেন্দ্রীয় স্থান्য।", en: "Demonstration of intended AI capabilities and visualisations. The primary AI is real." },
  demoAiRealTitle: { bn: "প্রচলিত এআই", en: "Real AI" },
  demoAiRealDesc: { bn: "সম্পূর্ণ ন্যারো ন্যারোল ল্যাঙ্গুয়েজ", en: "Fully deployed NLP" },
  demoAiRealNlp: { bn: "বাংলা / ইংরেজি মল্টিভাষীয় ন্যারো", en: "Bangla/English multilingual NLP" },
  demoAiRealPriority: { bn: "এআই অগ্রাধিকার ইংজিন", en: "AI priority scoring" },
  demoAiRealAuthority: { bn: "কর্তৃপক্ট রাউটিং", en: "Authority routing" },
  demoAiRealVoice: { bn: "চিহ্নিত ভয়েস", en: "Identified voice" },
  demoAiPrototypeTitle: { bn: "প্রোটোটাইপ", en: "PROTOTYPE" },
  demoAiPrototypeDesc: { bn: "ডেমোন্স্ট্রেশনের জন্য সামর্থ্যের মডেল", en: "Demonstration visualisations" },
  demoAiPrototypeVisual: { bn: "দৃশ্যমান প্রমাণ যাচাই", en: "Visual evidence check" },
  demoAiPrototypePredict: { bn: "এআই ঝুঁকি পূর্বানিমান", en: "Predictive risk" },
  demoAiPrototypeIntegrity: { bn: "প্রতিবেদনের সত্যতা", en: "Report integrity" },
  demoAiPrototypePrivacy: { bn: "স্বাচ্ছতা সুরক্ষা", en: "Privacy protection" },
  demoAiPrototypeSms: { bn: "এসএমএস", en: "SMS" },
  demoAiPrototypeUssd: { bn: "ইউএসএসএডি", en: "USSD" },
  demoAiPrototypeGphandoff: { bn: "জরুরী থেলে প্রতিনিধি", en: "Emergency warm handoff" },
  prototypeBadge: { bn: "প্রোটোটাইপ", en: "PROTOTYPE" },
  demoAiRealBadge: { bn: "প্রচলিত", en: "REAL" },
  demoAiLiveTitle: { bn: "প্রচলিত এআই নির্মাণ", en: "Live AI Understanding" },
  demoAiLivePrompt: { bn: "আপনার রিপোর্টের সাথে এআই এর উত্তর:", en: "Your report and the AI output:" },
  demoAiLiveNote: { bn: "এআই পাইপলাইন প্রোডাকশনে চলতেনের কেন্দ্রীয় এনজিনের ব্যবহৃত। প্রতিনিধি সব প্রোডাকশন ফীচারের জন্য ব্যবহৃত হচ্ছে।", en: "Real NLP pipeline running in production. Used by all production features." },
  category: { bn: "ক্যাটেগরি", en: "Category" },
  incident_type: { bn: "ঘটনার ধরন", en: "Incident type" },
  severity: { bn: "তীব্রতা", en: "Severity" },
  urgency: { bn: "জরুরীতা", en: "Urgency" },
  relevant_authority: { bn: "নির্দিষ্ট কর্তৃপক্ট", en: "Relevant authority" },
  priority_score: { bn: "অগ্রাধিকার", en: "Priority score" },
  model_confidence: { bn: "মডেল কনফিডেন্স", en: "Model confidence" },
  tileVisualTitle: { bn: "দৃশ্যমান প্রমাণ যাচাই", en: "Visual Evidence Check" },
  tileVisualSubtitle: { bn: "রিপোর্টের সাথে ঘটনার সামঞ্জস্য", en: "Consistency with the report" },
  tileVisualNote: { bn: "ডেমো অভিজ্ঞতা। নির্ণয় সিদ্ধান্তে।", en: "Demo experience with deterministic verdicts." },
  tilePredictTitle: { bn: "এআই ঝুঁকি পূর্বানিমান", en: "AI Risk Prediction" },
  tilePredictSubtitle: { bn: "অল্প কালে উন্নত সম্ভাবনা", en: "Higher risk at certain times" },
  tilePredictNote: { bn: "প্রোটোটাইপ। প্রচলিত পূর্বানিমান মডেল নয়।", en: "Prototype — no production model yet." },
  tilePredictSignal1: { bn: "সাম্প্রতিক সমস্যা", en: "Recent incidents" },
  tilePredictSignal2: { bn: "ইতিহাসের নমুনা", en: "Historical patterns" },
  tilePredictSignal3: { bn: "লোকেশন অন্যাচার", en: "Location activity" },
  tileIntegrityTitle: { bn: "এআই প্রতিবেদন সত্যতা", en: "AI Report Integrity" },
  tileIntegritySubtitle: { bn: "ডুলেট রিপোর্ট শনাকেন", en: "Detecting duplicate reports" },
  tileIntegrityBadge: { bn: "পর্যালোচনা হয়", en: "Review recommended" },
  tileIntegrityLine1: { bn: "৭ৱ সমান প্রতিবেদন", en: "7 similar reports" },
  tileIntegrityLine2: { bn: "৪ মিনিটের সময় পরিসর", en: "4-minute time window" },
  tileIntegrityLine3: { bn: "অতিপ্রস্পর্শ অবস্থান", en: "Overlapping location" },
  tileIntegrityNote: { bn: "প্রোটোটাইপ—মাত্রাইট নয়।", en: "Prototype—not a fraud detector yet." },
  tilePrivacyTitle: { bn: "এআই স্বাচ্ছতা সুরক্ষা", en: "AI Privacy Protection" },
  tilePrivacySubtitle: { bn: "উচ্চ স্তরের উন্নত ডেটা সুরক্ষা", en: "Higher-tier data protection" },
  tilePrivacyDetected1: { bn: "৩ৱ মুখের চেহারা শনাক্ত", en: "2 faces detected" },
  tilePrivacyDetected2: { bn: "১ৱ নাম পস্তার নম্বর", en: "1 license plate" },
  tilePrivacyOriginal: { bn: "অরিজিনাল", en: "Original" },
  tilePrivacyProtected: { bn: "সুরক্ষিত", en: "Protected" },
  tilePrivacyNote: { bn: "প্রোটোটাইপ—ডেমোন্স্ট্রেশন মাত্র।", en: "Prototype—demonstration only." },
  tileSmsTitle: { bn: "এসএমএস রিপোর্টিং", en: "SMS Reporting" },
  tileSmsSubtitle: { bn: "সরল এসএমএসের মাধ্যমে", en: "Plain text over SMS" },
  tileSmsNote: { bn: "প্রোটোটাইপ।", en: "Prototype." },
  tileUssdTitle: { bn: "ইউএসএসএডি", en: "USSD" },
  tileUssdSubtitle: { bn: "ইন্টরনেট না থাকলেও প্রপুরী সাথে মেনু", en: "Even without internet" },
  tileUssdNote: { bn: "প্রোটোচাইপ।", en: "Prototype." },
  tileGpTitle: { bn: "জরুরী থেলে প্রতিনিধি", en: "Emergency Warm Handoff" },
  tileGpSubtitle: { bn: "এসএমএসের মাধ্যমে", en: "Over SMS" },
  tileGpStation: { bn: "নিকটস্থ: মিরপুর পূলিশ স্টেশন", en: "Nearest: Mirpur Police Station" },
  tileGpItem1: { bn: "কালার অবস্থান", en: "Caller location" },
  tileGpItem2: { bn: "এসএমএসের সন্দর্ভ", en: "Incident context" },
  tileGpItem3: { bn: "জরুরী যোগাযোগ", en: "Emergency contact" },
  tileGpItem4: { bn: "আগের রিপোর্টের সন্দর্ভ", en: "Previous report context" },
  tileGpNote: { bn: "প্রোটোটাইপ।", en: "Prototype." },
  demoAiFootnote: { bn: "নিরাপন: প্রচলিত এআই + প্রোটোটাইপ মডেলের ডেমোন্স্ট্রেশন।", en: "Nirapod: real AI + prototype model demonstrations." },
  demoAiBackHome: { bn: "হোমে ফেরাই", en: "Back to home" },

  // Review step
  reportReview: { bn: "রিপোর্ট পর্যালোচনা", en: "Report review" },
  reviewDesc: {
    bn: "জমা দেওয়ার আগে সব বিবরণ একবার দেখে নিন।",
    en: "Review every detail before you submit.",
  },
  reviewIncident: { bn: "ঘটনা", en: "Incident" },
  reviewCategory: { bn: "ক্যাটেগরি", en: "Category" },
  reviewSeverity: { bn: "তীব্রতা", en: "Severity" },
  reviewUrgency: { bn: "জরুরী", en: "Urgency" },
  reviewLocation: { bn: "লোকেশন", en: "Location" },
  reviewVisual: { bn: "ভিজ্যুয়াল যাচাই", en: "Visual verification" },
  reviewAuthority: { bn: "কর্তৃপক্ষ", en: "Authority" },
  reviewPriority: { bn: "অগ্রাধিকার", en: "Priority" },
  editReport: { bn: "রিপোর্ট সম্পাদনা", en: "Edit Report" },
  submitReport: { bn: "রিপোর্ট জমা দিন", en: "Submit Report" },
  completeVerificationFirst: { bn: "আগে যাচাই সম্পন্ন করুন", en: "Complete verification first" },
  verifyingPhoto: { bn: "ছবি যাচাই হচ্ছে…", en: "Verifying photo…" },
  reviewAndSubmit: { bn: "রিভিউ করে জমা দিন", en: "Review & Submit" },
  submittingReport: { bn: "জমা দেওয়া হচ্ছে…", en: "Submitting report…" },
  submitFailed: { bn: "রিপোর্ট জমা দেওয়া যায়নি", en: "Could not submit report" },
  outOfServiceArea: { bn: "লোকেশন ঢাকা সার্ভিস এলাকার বাইরে", en: "Location is outside the Dhaka service area" },
  voiceTranscribed: { bn: "ভয়েস ট্রান্সক্রিপশন যোগ হয়েছে", en: "Voice transcription added" },
  voiceUnavailable: { bn: "ভয়েস ইনপুট এখন পাওয়া যাচ্ছে না", en: "Voice input unavailable right now" },
  stepIndicatorLabel: { bn: "ধাপ", en: "Step" },
};

type Ctx = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: keyof typeof strings | string) => string;
  textScale: TextScale;
  setTextScale: (s: TextScale) => void;
  highContrast: boolean;
  setHighContrast: (v: boolean) => void;

};

const AppContext = createContext<Ctx | null>(null);

export function AppProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("bn");
  const [textScale, setScaleState] = useState<TextScale>("base");
  const [highContrast, setContrastState] = useState(false);

  useEffect(() => {
    const l = localStorage.getItem("nd_lang") as Lang | null;
    if (l === "bn" || l === "en") setLangState(l);
    const s = localStorage.getItem("nd_scale") as TextScale | null;
    if (s === "base" || s === "lg" || s === "xl") setScaleState(s);
    setContrastState(localStorage.getItem("nd_contrast") === "1");
  }, []);

  useEffect(() => {
    const root = document.documentElement;
    root.lang = lang;
    root.classList.toggle("text-scale-lg", textScale === "lg");
    root.classList.toggle("text-scale-xl", textScale === "xl");
    root.classList.toggle("contrast-boost", highContrast);
  }, [lang, textScale, highContrast]);

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem("nd_lang", l);
  }, []);
  const setTextScale = useCallback((s: TextScale) => {
    setScaleState(s);
    localStorage.setItem("nd_scale", s);
  }, []);
  const setHighContrast = useCallback((v: boolean) => {
    setContrastState(v);
    localStorage.setItem("nd_contrast", v ? "1" : "0");
  }, []);

  const t = useCallback(
    (key: string) => {
      const entry = strings[key];
      if (!entry) return key;
      return entry[lang];
    },
    [lang],
  );

  const value = useMemo(
    () => ({ lang, setLang, t, textScale, setTextScale, highContrast, setHighContrast }),
    [lang, setLang, t, textScale, setTextScale, highContrast, setHighContrast],
  );

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error("useApp must be used inside AppProvider");
  return ctx;
}
